name: 'Commit Message Check'
on:
  workflow_call:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '(feat\(\):)|(fix\(\)):|(patch\(\)):|(perf\(\)):'
          flags: 'gm'
          error: 'Your first line has to contain a commit type like "feat(): or fix():".'